kind: pipeline
type: docker
name: default

volumes:
- name: dockersock
  temp: {}

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: lint
  image: golang:alpine
  environment:
    GOLINTCI_VERSION: v1.54.2
    CGO_ENABLED: 0
    GOOS: linux
  commands:
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLINTCI_VERSION}
  - golangci-lint --version
  - golangci-lint run
